trigger:
 branches:
    include:
      - main
 paths:
    include:
      - infra/ui/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/infra/ui'
    ArtifactName: 'build'
    publishLocation: 'Container'