# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: cd ./manager-server && npm install && npm run build
  displayName: 'Build Functions App'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/manager-server/dist'
    ArtifactName: 'build'
    publishLocation: 'Container'
